/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 animal2.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/animal2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['11506_Lion'].geometry} material={materials._11506_Lion_v3_FINALdefault} />
    </group>
  )
}

useGLTF.preload('/animal2.glb')
